spring:
  jackson:
    serialization:
      write-date-keys-as-timestamps: false
    date-time-format: ${JACKSON_DATE_FORMAT}
  application:
    name: ${APPLICATION_NAME}
  main:
    allow-circular-references: true
  datasource:
    url: ${DB_CONNECTION_STRING}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  flyway:
    baseline-on-migrate: true
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    password: ${MAIL_PASSWORD}
    username: ${MAIL_USERNAME}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  access-token:
    secret-key: ${SECRET_KEY}
    expired-duration: ${ACCESS_TOKEN_EXPIRED}
  refresh-token:
    expired-duration: ${REFRESH_TOKEN_EXPIRED}
  mail:
    username: ${MAIL_USERNAME}
    smtp:
      password: ${MAIL_SMTP_PASS}
  goong:
    key: ${GOONG_KEY}
    domain: ${GOONG_DOMAIN}
    autocomplete: ${GOONG_AUTOCOMPLETE}
    geocode: ${GOONG_GEOCODEs}

paw:
  verification:
    duration: ${PAW_VERIFICATION_DURATION}
  timeRange:
    distance: ${PAW_TIME_RANGE_DISTANCE}