spring:
  jackson:
    serialization:
      write-date-keys-as-timestamps: false
    date-time-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
  application:
    name: paw-fund-core-service
  main:
    allow-circular-references: true
  datasource:
    datasource:
      url: ${DB_CONNECTION_STRING}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  flyway:
    baseline-on-migrate: true
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    password: ${MAIL_PASSWORD}
    username: ${MAIL_USERNAME}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  access-token:
    secret-key: ftoLRVxHq82BzLq3stXhnOJRo4azrVab
    expired-duration: 4320
  refresh-token:
    expired-duration: 4320
  mail:
    username: brokenstar2197@gmail.com
    smtp:
      password: kqwb ipyc gkeh ligm
  goong:
    key: gMs7uHEjx646z9dVVjrh60fRPMADssbjc2Z7KYd1
    domain: https://rsapi.goong.io
    autocomplete: /Place/AutoComplete
    geocode: /geocode

paw:
  verification:
    duration: 15